### ISSUE TITLE
Trocar nome de Roupa de baixo (🩳) para caminhão (🚛)

### ISSUE THREAD

**Issue by allanvobraun** [ABNERMATHEUS/CRUD_Truncks#1]
Em todo o projeto esta escrito **Truncks**, quando na verdade acredito que o correto seria **Trucks**  ( de caminhões)

**Comment by ABNERMATHEUS** [comment]
Nossa, verdade mesmo 🤡

**Comment by ABNERMATHEUS** [comment]
Alterei tudo!! Obrigado!
